# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20190329_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='time_tamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
